menu:
    Blog: /
    Archive: /archives/
    Resume: /
    GitHub: https://github.com/sagittaria

favicon: /favicon.png
logo: /favicon.png

# Comment
# e.g disqus: seansun
disqus:
duoshuo:

# Analytics
# google-analytics:
ga: UA-65933410-1

# Copyright Infomation
startyear: 2015
